services:
  - type: web
    name: norix-security
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Norix Security
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://norix-security.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: norix-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: norix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: norix-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: norix-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: norix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: norix-db
          property: password

databases:
  - name: norix-db
    plan: free
    databaseName: norix
    user: norix
