<?php

return [
    'name' => 'Norix Security',
    'legal_name' => 'Norix Security Ltd',
    'tagline' => 'Precision protection across England\'s major cities',
    'description' => 'Norix Security provides SIA-licensed CCTV, mobile patrol, retail, events, door supervision, and manned guarding for B2B clients across England\'s major cities including London, Birmingham, Manchester, Leeds, Liverpool and beyond.',
    'phone' => '+44 20 7946 0958',
    'email' => 'hello@norixsecurity.co.uk',
    'careers_email' => 'careers@norixsecurity.co.uk',
    'address' => 'London, United Kingdom',
    'cities' => [
        ['name' => 'London', 'region' => 'Greater London', 'status' => 'active'],
        ['name' => 'Birmingham', 'region' => 'West Midlands', 'status' => 'active'],
        ['name' => 'Manchester', 'region' => 'Greater Manchester', 'status' => 'active'],
        ['name' => 'Leeds', 'region' => 'West Yorkshire', 'status' => 'active'],
        ['name' => 'Liverpool', 'region' => 'Merseyside', 'status' => 'active'],
        ['name' => 'Bristol', 'region' => 'South West', 'status' => 'active'],
        ['name' => 'Sheffield', 'region' => 'South Yorkshire', 'status' => 'active'],
        ['name' => 'Newcastle', 'region' => 'Tyne and Wear', 'status' => 'active'],
        ['name' => 'Nottingham', 'region' => 'East Midlands', 'status' => 'active'],
        ['name' => 'Leicester', 'region' => 'East Midlands', 'status' => 'active'],
        ['name' => 'Coventry', 'region' => 'West Midlands', 'status' => 'active'],
        ['name' => 'Southampton', 'region' => 'Hampshire', 'status' => 'active'],
        ['name' => 'Brighton', 'region' => 'East Sussex', 'status' => 'active'],
        ['name' => 'Reading', 'region' => 'Berkshire', 'status' => 'active'],
        ['name' => 'Plymouth', 'region' => 'Devon', 'status' => 'active'],
    ],
    'services' => [
        [
            'slug' => 'cctv-monitoring',
            'title' => 'CCTV Monitoring',
            'summary' => 'Licensed officers monitoring live feeds with incident logging and escalation.',
            'image' => 'images/service-cctv.jpg',
        ],
        [
            'slug' => 'manned-security',
            'title' => 'Manned Security',
            'summary' => 'Static officers for offices, warehouses, and critical commercial sites.',
            'image' => 'images/service-manned.jpg',
        ],
        [
            'slug' => 'door-supervisors',
            'title' => 'Door Supervisors',
            'summary' => 'SIA door supervisors for retail, leisure, and licensed venues.',
            'image' => 'images/service-door.jpg',
        ],
        [
            'slug' => 'events-security',
            'title' => 'Events Security',
            'summary' => 'Crowd-aware stewards and officers for corporate and public events.',
            'image' => 'images/service-events.jpg',
        ],
        [
            'slug' => 'keyholding-mobile',
            'title' => 'Keyholding & Mobile',
            'summary' => 'Alarm response and scheduled mobile patrols with branded visibility.',
            'image' => 'images/service-mobile.jpg',
        ],
        [
            'slug' => 'retail-guards',
            'title' => 'Retail & Shop Guards',
            'summary' => 'Customer-facing loss-prevention presence for high-street and centres.',
            'image' => 'images/service-retail.jpg',
        ],
    ],
];
